### PR TITLE
Add eth_SimulateV1 tests

### PR DESCRIPTION
**Pull request by KillariDev**
add tests for `eth_SimulateV1` RPC Method

### CODE REVIEW

**Comment by fjl** [comment]
It's a bad time to add this because we are currently rewriting how the test chain handling works in rpctestgen. I appreciate the contribution, but please wait a couple days until we have #27 in, and then we can add these tests.

**Comment by fjl** [comment]
The test contracts you added here look very useful, and we should put them into the `hivechain` tool that creates the new test chain. From what I can see, you need contracts that perform a specific behavior when called. We have some existing ones like that in hivechain, they are deployed into the chain like this: https://github.com/ethereum/hive/blob/master/cmd/hivechain/mod_deploy.go

Let me know if you have further questions about adding the contracts in hivechain. I will review the PR if you open one.

**Comment by fjl** [comment]
Ahh, right. So in this case, the contracts could remain here in this repo.

**Comment by KillariDev** [comment]
> PR probably still needs a rebase.

yeah, I have fixes to this in another repo. I am waiting for nethermind's eth_simulate client to fix couple of bugs before I make Pr here

**Pull request closed without merging**
